Repository atom/tree-view, pull requests merged in 2018-08, with the labels that each got.

#1069 Improve behavior of TreeView::moveUp() with nested directories
  lib/tree-view.coffee
  spec/tree-view-package-spec.coffee
Labels: under-review

#986 🐛 Deselect entries when non-directory file is opened.
  lib/tree-view.coffee
  spec/tree-view-package-spec.coffee
Labels: needs-review

#1266 Use shell.showItemInFolder to show files
  lib/tree-view.coffee
  menus/tree-view.cson
  spec/tree-view-package-spec.coffee
Labels: needs-testing
